//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// Microsoft.VSDesigner generó automáticamente este código fuente, versión=4.0.30319.42000.
// 
#pragma warning disable 1591

namespace WebPage.localhost {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="WebService1Soap", Namespace="http://tempuri.org/")]
    public partial class WebService1 : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback getUserByCredentialsOperationCompleted;
        
        private System.Threading.SendOrPostCallback getReservationByIDOperationCompleted;
        
        private System.Threading.SendOrPostCallback getRoomsOperationCompleted;
        
        private System.Threading.SendOrPostCallback createReservationOperationCompleted;
        
        private System.Threading.SendOrPostCallback updateReservationOperationCompleted;
        
        private System.Threading.SendOrPostCallback delateReservationOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public WebService1() {
            this.Url = global::WebPage.Properties.Settings.Default.WebPage_localhost_WebService1;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event getUserByCredentialsCompletedEventHandler getUserByCredentialsCompleted;
        
        /// <remarks/>
        public event getReservationByIDCompletedEventHandler getReservationByIDCompleted;
        
        /// <remarks/>
        public event getRoomsCompletedEventHandler getRoomsCompleted;
        
        /// <remarks/>
        public event createReservationCompletedEventHandler createReservationCompleted;
        
        /// <remarks/>
        public event updateReservationCompletedEventHandler updateReservationCompleted;
        
        /// <remarks/>
        public event delateReservationCompletedEventHandler delateReservationCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/getUserByCredentials", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public User getUserByCredentials(string email, string password) {
            object[] results = this.Invoke("getUserByCredentials", new object[] {
                        email,
                        password});
            return ((User)(results[0]));
        }
        
        /// <remarks/>
        public void getUserByCredentialsAsync(string email, string password) {
            this.getUserByCredentialsAsync(email, password, null);
        }
        
        /// <remarks/>
        public void getUserByCredentialsAsync(string email, string password, object userState) {
            if ((this.getUserByCredentialsOperationCompleted == null)) {
                this.getUserByCredentialsOperationCompleted = new System.Threading.SendOrPostCallback(this.OngetUserByCredentialsOperationCompleted);
            }
            this.InvokeAsync("getUserByCredentials", new object[] {
                        email,
                        password}, this.getUserByCredentialsOperationCompleted, userState);
        }
        
        private void OngetUserByCredentialsOperationCompleted(object arg) {
            if ((this.getUserByCredentialsCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.getUserByCredentialsCompleted(this, new getUserByCredentialsCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/getReservationByID", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public Reservation[] getReservationByID(int id, bool isClient) {
            object[] results = this.Invoke("getReservationByID", new object[] {
                        id,
                        isClient});
            return ((Reservation[])(results[0]));
        }
        
        /// <remarks/>
        public void getReservationByIDAsync(int id, bool isClient) {
            this.getReservationByIDAsync(id, isClient, null);
        }
        
        /// <remarks/>
        public void getReservationByIDAsync(int id, bool isClient, object userState) {
            if ((this.getReservationByIDOperationCompleted == null)) {
                this.getReservationByIDOperationCompleted = new System.Threading.SendOrPostCallback(this.OngetReservationByIDOperationCompleted);
            }
            this.InvokeAsync("getReservationByID", new object[] {
                        id,
                        isClient}, this.getReservationByIDOperationCompleted, userState);
        }
        
        private void OngetReservationByIDOperationCompleted(object arg) {
            if ((this.getReservationByIDCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.getReservationByIDCompleted(this, new getReservationByIDCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/getRooms", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public Room[] getRooms(bool availabe) {
            object[] results = this.Invoke("getRooms", new object[] {
                        availabe});
            return ((Room[])(results[0]));
        }
        
        /// <remarks/>
        public void getRoomsAsync(bool availabe) {
            this.getRoomsAsync(availabe, null);
        }
        
        /// <remarks/>
        public void getRoomsAsync(bool availabe, object userState) {
            if ((this.getRoomsOperationCompleted == null)) {
                this.getRoomsOperationCompleted = new System.Threading.SendOrPostCallback(this.OngetRoomsOperationCompleted);
            }
            this.InvokeAsync("getRooms", new object[] {
                        availabe}, this.getRoomsOperationCompleted, userState);
        }
        
        private void OngetRoomsOperationCompleted(object arg) {
            if ((this.getRoomsCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.getRoomsCompleted(this, new getRoomsCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/createReservation", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public bool createReservation(Reservation reservation) {
            object[] results = this.Invoke("createReservation", new object[] {
                        reservation});
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        public void createReservationAsync(Reservation reservation) {
            this.createReservationAsync(reservation, null);
        }
        
        /// <remarks/>
        public void createReservationAsync(Reservation reservation, object userState) {
            if ((this.createReservationOperationCompleted == null)) {
                this.createReservationOperationCompleted = new System.Threading.SendOrPostCallback(this.OncreateReservationOperationCompleted);
            }
            this.InvokeAsync("createReservation", new object[] {
                        reservation}, this.createReservationOperationCompleted, userState);
        }
        
        private void OncreateReservationOperationCompleted(object arg) {
            if ((this.createReservationCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.createReservationCompleted(this, new createReservationCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/updateReservation", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public bool updateReservation(Reservation reservation) {
            object[] results = this.Invoke("updateReservation", new object[] {
                        reservation});
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        public void updateReservationAsync(Reservation reservation) {
            this.updateReservationAsync(reservation, null);
        }
        
        /// <remarks/>
        public void updateReservationAsync(Reservation reservation, object userState) {
            if ((this.updateReservationOperationCompleted == null)) {
                this.updateReservationOperationCompleted = new System.Threading.SendOrPostCallback(this.OnupdateReservationOperationCompleted);
            }
            this.InvokeAsync("updateReservation", new object[] {
                        reservation}, this.updateReservationOperationCompleted, userState);
        }
        
        private void OnupdateReservationOperationCompleted(object arg) {
            if ((this.updateReservationCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.updateReservationCompleted(this, new updateReservationCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/delateReservation", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public bool delateReservation(int idReservation) {
            object[] results = this.Invoke("delateReservation", new object[] {
                        idReservation});
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        public void delateReservationAsync(int idReservation) {
            this.delateReservationAsync(idReservation, null);
        }
        
        /// <remarks/>
        public void delateReservationAsync(int idReservation, object userState) {
            if ((this.delateReservationOperationCompleted == null)) {
                this.delateReservationOperationCompleted = new System.Threading.SendOrPostCallback(this.OndelateReservationOperationCompleted);
            }
            this.InvokeAsync("delateReservation", new object[] {
                        idReservation}, this.delateReservationOperationCompleted, userState);
        }
        
        private void OndelateReservationOperationCompleted(object arg) {
            if ((this.delateReservationCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.delateReservationCompleted(this, new delateReservationCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class User {
        
        private int idField;
        
        private string emailField;
        
        private string passwordField;
        
        private string nameField;
        
        private TypeUser typeField;
        
        /// <remarks/>
        public int Id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
            }
        }
        
        /// <remarks/>
        public string Email {
            get {
                return this.emailField;
            }
            set {
                this.emailField = value;
            }
        }
        
        /// <remarks/>
        public string Password {
            get {
                return this.passwordField;
            }
            set {
                this.passwordField = value;
            }
        }
        
        /// <remarks/>
        public string Name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
            }
        }
        
        /// <remarks/>
        public TypeUser Type {
            get {
                return this.typeField;
            }
            set {
                this.typeField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public enum TypeUser {
        
        /// <remarks/>
        Client,
        
        /// <remarks/>
        Recepcionist,
        
        /// <remarks/>
        NotFound,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class Room {
        
        private int idField;
        
        private string typeRoomField;
        
        private string nameField;
        
        private string descriptionField;
        
        private float priceField;
        
        private bool availableField;
        
        /// <remarks/>
        public int ID {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
            }
        }
        
        /// <remarks/>
        public string TypeRoom {
            get {
                return this.typeRoomField;
            }
            set {
                this.typeRoomField = value;
            }
        }
        
        /// <remarks/>
        public string Name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
            }
        }
        
        /// <remarks/>
        public string Description {
            get {
                return this.descriptionField;
            }
            set {
                this.descriptionField = value;
            }
        }
        
        /// <remarks/>
        public float Price {
            get {
                return this.priceField;
            }
            set {
                this.priceField = value;
            }
        }
        
        /// <remarks/>
        public bool Available {
            get {
                return this.availableField;
            }
            set {
                this.availableField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class Reservation {
        
        private int idField;
        
        private int idClientField;
        
        private int idRecepcionistField;
        
        private Room roomField;
        
        private string nameField;
        
        private string arrivalDateField;
        
        private int nightsField;
        
        /// <remarks/>
        public int Id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
            }
        }
        
        /// <remarks/>
        public int IdClient {
            get {
                return this.idClientField;
            }
            set {
                this.idClientField = value;
            }
        }
        
        /// <remarks/>
        public int IdRecepcionist {
            get {
                return this.idRecepcionistField;
            }
            set {
                this.idRecepcionistField = value;
            }
        }
        
        /// <remarks/>
        public Room Room {
            get {
                return this.roomField;
            }
            set {
                this.roomField = value;
            }
        }
        
        /// <remarks/>
        public string Name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
            }
        }
        
        /// <remarks/>
        public string ArrivalDate {
            get {
                return this.arrivalDateField;
            }
            set {
                this.arrivalDateField = value;
            }
        }
        
        /// <remarks/>
        public int Nights {
            get {
                return this.nightsField;
            }
            set {
                this.nightsField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    public delegate void getUserByCredentialsCompletedEventHandler(object sender, getUserByCredentialsCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class getUserByCredentialsCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal getUserByCredentialsCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public User Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((User)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    public delegate void getReservationByIDCompletedEventHandler(object sender, getReservationByIDCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class getReservationByIDCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal getReservationByIDCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public Reservation[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((Reservation[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    public delegate void getRoomsCompletedEventHandler(object sender, getRoomsCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class getRoomsCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal getRoomsCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public Room[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((Room[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    public delegate void createReservationCompletedEventHandler(object sender, createReservationCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class createReservationCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal createReservationCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public bool Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    public delegate void updateReservationCompletedEventHandler(object sender, updateReservationCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class updateReservationCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal updateReservationCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public bool Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    public delegate void delateReservationCompletedEventHandler(object sender, delateReservationCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class delateReservationCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal delateReservationCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public bool Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591